class Params {
    isPaused = false;
    boidSize = 5;
    lineMaxDist = 150;
    WallThickness = 0;
    WallBuffer = 50;
    InitialPopulation = 10;
    MaxPopulation = 150;
    MaxSpeed = 3;
    MinSpeed = 2.5;
    MaxForce = 0.2;
    SeperationWeight = 5;
    AlignmentWeight = 1.5;
    CohesionWeight = 1.5;
    SphereOfInfluence = 50;
    CohesionNeighborhood = 100;
    DesiredSeperation = 25;
    SimulationSpeed = 10;
}
export default Params;
